upstream farm2 {
    server 127.0.0.1:3000;
}

# ポート80: Let's Encrypt用
server {
    listen 80;
    server_name shimo-dekisu.farm;

    # Let's Encrypt 認証用
    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    # HTTP -> HTTPS へリダイレクト（Let's Encrypt チャレンジ以外）
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name shimo-dekisu.farm;

    ssl_certificate /etc/letsencrypt/live/shimo-dekisu.farm/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shimo-dekisu.farm/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /opt/app/farm2/public;

    location /farm2/assets/ {
        alias /opt/app/farm2/public/assets/;
        try_files $uri =404;
        access_log off;
        expires max;
        add_header Cache-Control public;
        autoindex off;
    }

    location /farm2/images/ {
	alias /opt/app/farm2/public/images/;
	try_files $uri =404;
	access_log off;
	expires max;
	add_header Cache-Control public;
	autoindex off;
    }

    location /farm2/javascripts/ {
	alias /opt/app/farm2/public/javascripts/;
	try_files $uri =404;
	access_log off;
	expires max;
	add_header Cache-Control public;
	autoindex off;
    }

    location / {
        root /var/www/shimo-dekisu.farm;
        index index.html;
    }

    location /farm2 {
	    return 301 /farm2/;
    }

    location /farm2/cable {
        proxy_pass http://farm2/cable;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /farm2;
        proxy_set_header X-Script-Name /farm2;
        proxy_redirect off;
    }

    location /farm2/ {
        proxy_pass http://farm2/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /farm2;
        proxy_set_header X-Script-Name /farm2;
        proxy_redirect off;
    }

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    error_page 500 502 503 504 /500.html;
    client_max_body_size 4G;
    keepalive_timeout 10;
}
