Documentation:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

HashSyntax:
  Enabled: false

MethodName:
  Enabled: false

StringLiterals:
  Enabled: false

# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false
