Documentation:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

HashSyntax:
  Enabled: false

MethodName:
  Enabled: false

StringLiterals:
  Enabled: false

# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 11

Style/RedundantReturn:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 0
  SupportedStyles:
    - percent
    - brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/BracesAroundHashParameters:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space

Layout/EndOfLine:
  EnforcedStyle: lf
