services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-production
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        MAIL_ADDRESS: ${MAIL_ADDRESS}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    tty: true
    stdin_open: true
    environment:
      - API_KEY=${GOOGLE_MAPS_API_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
      - ./config/postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - .env:/opt/app/farm2/.env
    env_file:
      - .env
volumes:
  dbdata_production:
