version: "3.9"
services:
  db:
    image: postgres:13
    volumes:
      - type: volume
        source: dbdata_test
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: farm2_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: ./Dockerfile-test
    command: bundle exec rake test
    volumes:
      - type: bind
        source: .
        target: /farm2
    depends_on:
      - db

volumes:
   dbdata_test:
