version: "3.9"
services:
  db:
    image: postgres:13
    volumes:
      - type: volume
        source: dbdata_test
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: farm2_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app_test:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec rake test:system
    volumes:
      - type: bind
        source: .
        target: /farm2
    depends_on:
      - db

  chrome:
    image: browserless/chrome
    ports:
      - "3333:3333"
    environment:
      PORT: 3333

volumes:
   dbdata_test:
