services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-production
    tty: true
    stdin_open: true
    environment:
      - API_KEY=${GOOGLE_MAPS_API_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "80:80"
      - "5432:5432"
    volumes:
      - type: volume
        source: dbdata_production
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

volumes:
  dbdata_production:
