- id: 10
  code: SEEDLING
  name: "種苗"
- id: 20
  code: CHEMICAL
  name: "薬品"
- id: 30
  code: FUEL
  name: "燃料"
- id: 40
  code: MACHINE
  name: "機械"
- id: 50
  code: PACK
  name: "梱包"
- id: 99
  code: OTHER
  name: "その他"
