- id: 10
  code: SEEDLING
  name: "種苗"
  direct: Yes
- id: 20
  code: CHEMICAL
  name: "薬品"
  direct: Yes
- id: 30
  code: FUEL
  name: "燃料"
  direct: Yes
- id: 40
  code: MACHINE
  name: "機械"
  direct: Yes
- id: 50
  code: PACK
  name: "梱包"
  direct: Yes
- id: 99
  code: OTHER1
  name: "その他(直接)"
  direct: Yes
- id: 110
  code: UTILITY
  name: "水道光熱"
  direct: No
- id: 130
  code: COM
  name: "通信"
  direct: No
- id: 140
  code: DESK
  name: "事務"
  direct: No
- id: 199
  code: OTHER2
  name: "その他(間接)"
  direct: No
