- id: 10
  code: Land
  name: "土地(管理)"
- id: 15
  code: Peasant
  name: "土地(小作)"
- id: 20
  code: Depreciation
  name: "減価償却"
- id: 30
  code: WorkWorker
  name: "作業(作業者)"
- id: 40
  code: WorkMachine
  name: "作業(機械使用)"
- id: 50
  code: WorkFuel
  name: "作業(燃料)"
- id: 60
  code: WorkChemical
  name: "作業(薬剤)"
- id: 70
  code: Seedling
  name: "育苗"
- id: 80
  code: Dry
  name: "乾燥・調整"
- id: 90
  code: ExpenseDirect
  name: "経費(直接)"
- id: 95
  code: SaleCost
  name: "販売経費"
- id: 101
  code: WorkIndirect
  name: "作業(間接)"
- id: 110
  code: ExpenseIndirect
  name: "経費(間接)"
- id: 200
  code: Sales
  name: "売上"
- id: 210
  code: Subsidy
  name: "助成金"
- id: 300
  code: Machine
  name: "機械稼働"
