- id: 10
  code: WorkWorker
  name: "作業(作業者)"
- id: 20
  code: WorkMachine
  name: "作業(機械使用)"
- id: 30
  code: WorkFuel
  name: "作業(燃料)"
- id: 40
  code: WorkChemical
  name: "作業(薬剤)"
- id: 50
  code: Seedling
  name: "育苗"
- id: 60
  code: Dry
  name: "乾燥・調整"
- id: 80
  code: Land
  name: "土地管理"
- id: 90
  code: Expense
  name: "経費"
- id: 100
  code: Sales
  name: "売上"
