- id: 1
  code: Area
  name: "土地(面積)"
  account: false
- id: 10
  code: Land
  name: "土地(管理)"
  account: false
- id: 15
  code: Peasant
  name: "土地(小作)"
  account: false
- id: 20
  code: Depreciation
  name: "減価償却"
  account: false
- id: 30
  code: WorkWorker
  name: "作業(作業者)"
  account: false
- id: 40
  code: WorkMachine
  name: "作業(機械使用)"
  account: false
- id: 50
  code: WorkFuel
  name: "作業(燃料)"
  account: false
- id: 60
  code: WorkChemical
  name: "作業(薬剤)"
  account: false
- id: 70
  code: Seedling
  name: "育苗"
  account: false
- id: 80
  code: Dry
  name: "乾燥・調整"
  account: false
- id: 90
  code: ExpenseDirect
  name: "生産原価"
  account: true
  debit: true
- id: 101
  code: WorkIndirect
  name: "作業(間接)"
  account: false
- id: 110
  code: ExpenseIndirect
  name: "一般管理費"
  account: true
  debit: true
- id: 200
  code: Sales
  name: "売上"
  account: true
  debit: false
- id: 210
  code: Subsidy
  name: "助成金"
  account: false
- id: 300
  code: Machine
  name: "機械稼働"
  account: false
