- id: 1
  code: WorkWorker
  name: "作業(作業者)"
- id: 2
  code: WorkMachine
  name: "作業(機械)"
- id: 3
  code: WorkFuel
  name: "作業(燃料)"
- id: 4
  code: WorkChemical
  name: "作業(薬剤)"
- id: 5
  code: Seedling
  name: "育苗"
- id: 9
  code: Expense
  name: "経費"
